"""Initial migration: create all tables

Revision ID: 8cc48bf27d5a
Revises:
Create Date: 2026-03-30 13:16:21.194099

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cc48bf27d5a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", "interval", name="uq_symbol_timestamp_interval"),
    )
    op.create_index(
        "idx_symbol_interval_time", "market_data", ["symbol", "interval", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_market_data_symbol"), "market_data", ["symbol"], unique=False)
    op.create_index(op.f("ix_market_data_timestamp"), "market_data", ["timestamp"], unique=False)
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_module_level_time", "system_logs", ["module", "level", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_system_logs_level"), "system_logs", ["level"], unique=False)
    op.create_index(op.f("ix_system_logs_module"), "system_logs", ["module"], unique=False)
    op.create_index(op.f("ix_system_logs_timestamp"), "system_logs", ["timestamp"], unique=False)
    op.create_table(
        "trading_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("initial_balance", sa.Float(), nullable=False),
        sa.Column("current_balance", sa.Float(), nullable=False),
        sa.Column("profit_loss", sa.Float(), nullable=False),
        sa.Column("profit_loss_percent", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_session_strategy", "trading_sessions", ["session_id", "strategy_id"], unique=False
    )
    op.create_index(
        "idx_session_symbol", "trading_sessions", ["session_id", "symbol"], unique=False
    )
    op.create_index(
        op.f("ix_trading_sessions_session_id"), "trading_sessions", ["session_id"], unique=True
    )
    op.create_index(
        op.f("ix_trading_sessions_strategy_id"), "trading_sessions", ["strategy_id"], unique=False
    )
    op.create_index(
        op.f("ix_trading_sessions_symbol"), "trading_sessions", ["symbol"], unique=False
    )
    op.create_table(
        "strategy_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("metric_type", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_strategy_metric_time",
        "strategy_metrics",
        ["strategy_id", "metric_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_strategy_session_metric",
        "strategy_metrics",
        ["strategy_id", "session_id", "metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strategy_metrics_metric_name"), "strategy_metrics", ["metric_name"], unique=False
    )
    op.create_index(
        op.f("ix_strategy_metrics_session_id"), "strategy_metrics", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_strategy_metrics_strategy_id"), "strategy_metrics", ["strategy_id"], unique=False
    )
    op.create_index(
        op.f("ix_strategy_metrics_timestamp"), "strategy_metrics", ["timestamp"], unique=False
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("filled_quantity", sa.Float(), nullable=False),
        sa.Column("avg_fill_price", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("commission", sa.Float(), nullable=False),
        sa.Column("pnl", sa.Float(), nullable=False),
        sa.Column("pnl_percent", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trade_session", "trades", ["trade_id", "session_id"], unique=False)
    op.create_index("idx_trade_strategy", "trades", ["trade_id", "strategy_id"], unique=False)
    op.create_index("idx_trade_symbol_time", "trades", ["symbol", "created_at"], unique=False)
    op.create_index(op.f("ix_trades_session_id"), "trades", ["session_id"], unique=False)
    op.create_index(op.f("ix_trades_strategy_id"), "trades", ["strategy_id"], unique=False)
    op.create_index(op.f("ix_trades_symbol"), "trades", ["symbol"], unique=False)
    op.create_index(op.f("ix_trades_trade_id"), "trades", ["trade_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_trade_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_symbol"), table_name="trades")
    op.drop_index(op.f("ix_trades_strategy_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_session_id"), table_name="trades")
    op.drop_index("idx_trade_symbol_time", table_name="trades")
    op.drop_index("idx_trade_strategy", table_name="trades")
    op.drop_index("idx_trade_session", table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_strategy_metrics_timestamp"), table_name="strategy_metrics")
    op.drop_index(op.f("ix_strategy_metrics_strategy_id"), table_name="strategy_metrics")
    op.drop_index(op.f("ix_strategy_metrics_session_id"), table_name="strategy_metrics")
    op.drop_index(op.f("ix_strategy_metrics_metric_name"), table_name="strategy_metrics")
    op.drop_index("idx_strategy_session_metric", table_name="strategy_metrics")
    op.drop_index("idx_strategy_metric_time", table_name="strategy_metrics")
    op.drop_table("strategy_metrics")
    op.drop_index(op.f("ix_trading_sessions_symbol"), table_name="trading_sessions")
    op.drop_index(op.f("ix_trading_sessions_strategy_id"), table_name="trading_sessions")
    op.drop_index(op.f("ix_trading_sessions_session_id"), table_name="trading_sessions")
    op.drop_index("idx_session_symbol", table_name="trading_sessions")
    op.drop_index("idx_session_strategy", table_name="trading_sessions")
    op.drop_table("trading_sessions")
    op.drop_index(op.f("ix_system_logs_timestamp"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_module"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_level"), table_name="system_logs")
    op.drop_index("idx_module_level_time", table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index(op.f("ix_market_data_timestamp"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_symbol"), table_name="market_data")
    op.drop_index("idx_symbol_interval_time", table_name="market_data")
    op.drop_table("market_data")
    # ### end Alembic commands ###
