allow-lan: true
log-level: info
mixed-port: 7890
mode: rule
proxies:
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-01
  network: ws
  port: 443
  server: 104.17.105.48
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-02
  network: ws
  port: 80
  server: 104.17.105.48
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-03
  network: ws
  port: 443
  server: 104.17.178.160
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-04
  network: ws
  port: 80
  server: 104.17.178.160
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 移动-SJC-443-WS-TLS-01
  network: ws
  port: 443
  server: 162.159.32.64
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 移动-SJC-80-WS-02
  network: ws
  port: 80
  server: 162.159.32.64
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-05
  network: ws
  port: 443
  server: 104.17.19.5
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-06
  network: ws
  port: 80
  server: 104.17.19.5
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-07
  network: ws
  port: 443
  server: 104.16.156.126
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-08
  network: ws
  port: 80
  server: 104.16.156.126
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-01
  network: ws
  port: 443
  server: 104.17.150.190
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-02
  network: ws
  port: 80
  server: 104.17.150.190
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-03
  network: ws
  port: 443
  server: 104.17.144.200
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-04
  network: ws
  port: 80
  server: 104.17.144.200
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-LAX-443-WS-TLS-01
  network: ws
  port: 443
  server: 162.159.44.228
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-LAX-80-WS-02
  network: ws
  port: 80
  server: 162.159.44.228
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-05
  network: ws
  port: 443
  server: 104.17.153.122
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-06
  network: ws
  port: 80
  server: 104.17.153.122
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-07
  network: ws
  port: 443
  server: 104.17.153.113
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-08
  network: ws
  port: 80
  server: 104.17.153.113
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-01
  network: ws
  port: 443
  server: 172.64.34.170
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-02
  network: ws
  port: 80
  server: 172.64.34.170
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-NRT-443-WS-TLS-01
  network: ws
  port: 443
  server: 162.159.38.78
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-NRT-80-WS-02
  network: ws
  port: 80
  server: 162.159.38.78
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-NRT-443-WS-TLS-03
  network: ws
  port: 443
  server: 162.159.38.57
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-NRT-80-WS-04
  network: ws
  port: 80
  server: 162.159.38.57
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-NRT-443-WS-TLS-05
  network: ws
  port: 443
  server: 162.159.45.99
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-NRT-80-WS-06
  network: ws
  port: 80
  server: 162.159.45.99
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-NRT-443-WS-TLS-07
  network: ws
  port: 443
  server: 162.159.44.77
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-NRT-80-WS-08
  network: ws
  port: 80
  server: 162.159.44.77
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 移动-SJC-443-WS-TLS-03
  network: ws
  port: 443
  server: 2606:4700:4408::ab46:bbc1
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 移动-SJC-80-WS-04
  network: ws
  port: 80
  server: 2606:4700:4408::ab46:bbc1
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 移动-SJC-443-WS-TLS-05
  network: ws
  port: 443
  server: 2606:4700:4700::e4ca:e2a4
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 移动-SJC-80-WS-06
  network: ws
  port: 80
  server: 2606:4700:4700::e4ca:e2a4
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 移动-SJC-443-WS-TLS-07
  network: ws
  port: 443
  server: 2a06:98c1:3108::5d3e:48e4
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 移动-SJC-80-WS-08
  network: ws
  port: 80
  server: 2a06:98c1:3108::5d3e:48e4
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 移动-SJC-443-WS-TLS-09
  network: ws
  port: 443
  server: 2803:f800:54::9ff2:fd05
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 移动-SJC-80-WS-10
  network: ws
  port: 80
  server: 2803:f800:54::9ff2:fd05
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 移动-SJC-443-WS-TLS-11
  network: ws
  port: 443
  server: 2606:4700:440c::a6eb:c74b
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 移动-SJC-80-WS-12
  network: ws
  port: 80
  server: 2606:4700:440c::a6eb:c74b
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-03
  network: ws
  port: 443
  server: 2606:4700:4700::6214:ed20
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-04
  network: ws
  port: 80
  server: 2606:4700:4700::6214:ed20
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-05
  network: ws
  port: 443
  server: 2a06:98c1:3104::7468:baf2
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-06
  network: ws
  port: 80
  server: 2a06:98c1:3104::7468:baf2
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-07
  network: ws
  port: 443
  server: 2606:4700:440c::a6eb:c74b
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-08
  network: ws
  port: 80
  server: 2606:4700:440c::a6eb:c74b
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-09
  network: ws
  port: 443
  server: 2803:f800:54::9ff2:fd05
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-10
  network: ws
  port: 80
  server: 2803:f800:54::9ff2:fd05
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-11
  network: ws
  port: 443
  server: 2a06:98c1:310e::59bb:ff9d
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-12
  network: ws
  port: 80
  server: 2a06:98c1:310e::59bb:ff9d
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
proxy-groups:
- name: 🚀 节点选择
  proxies:
  - ♻️ 自动选择
  - 🇭🇰 移动-HKG-443-WS-TLS-01
  - 🇭🇰 移动-HKG-80-WS-02
  - 🇭🇰 移动-HKG-443-WS-TLS-03
  - 🇭🇰 移动-HKG-80-WS-04
  - 移动-SJC-443-WS-TLS-01
  - 移动-SJC-80-WS-02
  - 🇭🇰 移动-HKG-443-WS-TLS-05
  - 🇭🇰 移动-HKG-80-WS-06
  - 🇭🇰 移动-HKG-443-WS-TLS-07
  - 🇭🇰 移动-HKG-80-WS-08
  - 联通-SJC-443-WS-TLS-01
  - 联通-SJC-80-WS-02
  - 联通-SJC-443-WS-TLS-03
  - 联通-SJC-80-WS-04
  - 联通-LAX-443-WS-TLS-01
  - 联通-LAX-80-WS-02
  - 联通-SJC-443-WS-TLS-05
  - 联通-SJC-80-WS-06
  - 联通-SJC-443-WS-TLS-07
  - 联通-SJC-80-WS-08
  - 电信-SIN-443-WS-TLS-01
  - 电信-SIN-80-WS-02
  - 电信-NRT-443-WS-TLS-01
  - 电信-NRT-80-WS-02
  - 电信-NRT-443-WS-TLS-03
  - 电信-NRT-80-WS-04
  - 电信-NRT-443-WS-TLS-05
  - 电信-NRT-80-WS-06
  - 电信-NRT-443-WS-TLS-07
  - 电信-NRT-80-WS-08
  - 移动-SJC-443-WS-TLS-03
  - 移动-SJC-80-WS-04
  - 移动-SJC-443-WS-TLS-05
  - 移动-SJC-80-WS-06
  - 移动-SJC-443-WS-TLS-07
  - 移动-SJC-80-WS-08
  - 移动-SJC-443-WS-TLS-09
  - 移动-SJC-80-WS-10
  - 移动-SJC-443-WS-TLS-11
  - 移动-SJC-80-WS-12
  - 电信-SIN-443-WS-TLS-03
  - 电信-SIN-80-WS-04
  - 电信-SIN-443-WS-TLS-05
  - 电信-SIN-80-WS-06
  - 电信-SIN-443-WS-TLS-07
  - 电信-SIN-80-WS-08
  - 电信-SIN-443-WS-TLS-09
  - 电信-SIN-80-WS-10
  - 电信-SIN-443-WS-TLS-11
  - 电信-SIN-80-WS-12
  - 🎯 全球直连
  type: select
- interval: 300
  name: ♻️ 自动选择
  proxies:
  - 🇭🇰 移动-HKG-443-WS-TLS-01
  - 🇭🇰 移动-HKG-80-WS-02
  - 🇭🇰 移动-HKG-443-WS-TLS-03
  - 🇭🇰 移动-HKG-80-WS-04
  - 移动-SJC-443-WS-TLS-01
  - 移动-SJC-80-WS-02
  - 🇭🇰 移动-HKG-443-WS-TLS-05
  - 🇭🇰 移动-HKG-80-WS-06
  - 🇭🇰 移动-HKG-443-WS-TLS-07
  - 🇭🇰 移动-HKG-80-WS-08
  - 联通-SJC-443-WS-TLS-01
  - 联通-SJC-80-WS-02
  - 联通-SJC-443-WS-TLS-03
  - 联通-SJC-80-WS-04
  - 联通-LAX-443-WS-TLS-01
  - 联通-LAX-80-WS-02
  - 联通-SJC-443-WS-TLS-05
  - 联通-SJC-80-WS-06
  - 联通-SJC-443-WS-TLS-07
  - 联通-SJC-80-WS-08
  - 电信-SIN-443-WS-TLS-01
  - 电信-SIN-80-WS-02
  - 电信-NRT-443-WS-TLS-01
  - 电信-NRT-80-WS-02
  - 电信-NRT-443-WS-TLS-03
  - 电信-NRT-80-WS-04
  - 电信-NRT-443-WS-TLS-05
  - 电信-NRT-80-WS-06
  - 电信-NRT-443-WS-TLS-07
  - 电信-NRT-80-WS-08
  - 移动-SJC-443-WS-TLS-03
  - 移动-SJC-80-WS-04
  - 移动-SJC-443-WS-TLS-05
  - 移动-SJC-80-WS-06
  - 移动-SJC-443-WS-TLS-07
  - 移动-SJC-80-WS-08
  - 移动-SJC-443-WS-TLS-09
  - 移动-SJC-80-WS-10
  - 移动-SJC-443-WS-TLS-11
  - 移动-SJC-80-WS-12
  - 电信-SIN-443-WS-TLS-03
  - 电信-SIN-80-WS-04
  - 电信-SIN-443-WS-TLS-05
  - 电信-SIN-80-WS-06
  - 电信-SIN-443-WS-TLS-07
  - 电信-SIN-80-WS-08
  - 电信-SIN-443-WS-TLS-09
  - 电信-SIN-80-WS-10
  - 电信-SIN-443-WS-TLS-11
  - 电信-SIN-80-WS-12
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: 🎯 全球直连
  proxies:
  - DIRECT
  type: select
- name: 🛑 全球拦截
  proxies:
  - REJECT
  type: select
rules:
- DOMAIN-SUFFIX,local,🎯 全球直连
- IP-CIDR,127.0.0.0/8,🎯 全球直连
- IP-CIDR,172.16.0.0/12,🎯 全球直连
- IP-CIDR,192.168.0.0/16,🎯 全球直连
- IP-CIDR,10.0.0.0/8,🎯 全球直连
- IP-CIDR,100.64.0.0/10,🎯 全球直连
- DOMAIN,ad.com,🛑 全球拦截
- DOMAIN,ad.doubler.com,🛑 全球拦截
- DOMAIN-SUFFIX,ad.doubler.com,🛑 全球拦截
- DOMAIN,ad.doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,ad.doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,googlesyndication.com,🛑 全球拦截
- DOMAIN-SUFFIX,googleadservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,doubleclick.net,🛑 全球拦截
- GEOIP,LAN,🎯 全球直连
- GEOIP,CN,🎯 全球直连
- MATCH,🚀 节点选择
