allow-lan: true
log-level: info
mixed-port: 7890
mode: rule
proxies:
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-01
  network: ws
  port: 443
  server: 104.25.252.153
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-02
  network: ws
  port: 80
  server: 104.25.252.153
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-03
  network: ws
  port: 443
  server: 104.25.243.230
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-04
  network: ws
  port: 80
  server: 104.25.243.230
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-05
  network: ws
  port: 443
  server: 104.25.243.200
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-06
  network: ws
  port: 80
  server: 104.25.243.200
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-07
  network: ws
  port: 443
  server: 104.25.252.242
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-08
  network: ws
  port: 80
  server: 104.25.252.242
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 🇭🇰 移动-HKG-443-WS-TLS-09
  network: ws
  port: 443
  server: 104.25.245.139
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 🇭🇰 移动-HKG-80-WS-10
  network: ws
  port: 80
  server: 104.25.245.139
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-01
  network: ws
  port: 443
  server: 104.17.135.241
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-02
  network: ws
  port: 80
  server: 104.17.135.241
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-03
  network: ws
  port: 443
  server: 104.17.131.151
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-04
  network: ws
  port: 80
  server: 104.17.131.151
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-05
  network: ws
  port: 443
  server: 104.17.154.130
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-06
  network: ws
  port: 80
  server: 104.17.154.130
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-07
  network: ws
  port: 443
  server: 104.17.135.175
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-08
  network: ws
  port: 80
  server: 104.17.135.175
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 联通-SJC-443-WS-TLS-09
  network: ws
  port: 443
  server: 172.64.79.185
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 联通-SJC-80-WS-10
  network: ws
  port: 80
  server: 172.64.79.185
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-01
  network: ws
  port: 443
  server: 173.245.59.161
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-02
  network: ws
  port: 80
  server: 173.245.59.161
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-03
  network: ws
  port: 443
  server: 162.159.22.251
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-04
  network: ws
  port: 80
  server: 162.159.22.251
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-05
  network: ws
  port: 443
  server: 162.159.27.166
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-06
  network: ws
  port: 80
  server: 162.159.27.166
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-07
  network: ws
  port: 443
  server: 162.159.3.230
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-08
  network: ws
  port: 80
  server: 162.159.3.230
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- client-fingerprint: randomized
  name: 电信-SIN-443-WS-TLS-09
  network: ws
  port: 443
  server: 162.159.6.101
  servername: dy.qlsm.net
  skip-cert-verify: false
  tfo: false
  tls: true
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
- name: 电信-SIN-80-WS-10
  network: ws
  port: 80
  server: 162.159.6.101
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  uuid: 7782bcd0-7448-4f69-8014-00f6c9867956
  ws-opts:
    headers:
      Host: dy.qlsm.net
    path: /?ed=2048
proxy-groups:
- name: 🚀 节点选择
  proxies:
  - ♻️ 自动选择
  - 🇭🇰 移动-HKG-443-WS-TLS-01
  - 🇭🇰 移动-HKG-80-WS-02
  - 🇭🇰 移动-HKG-443-WS-TLS-03
  - 🇭🇰 移动-HKG-80-WS-04
  - 🇭🇰 移动-HKG-443-WS-TLS-05
  - 🇭🇰 移动-HKG-80-WS-06
  - 🇭🇰 移动-HKG-443-WS-TLS-07
  - 🇭🇰 移动-HKG-80-WS-08
  - 🇭🇰 移动-HKG-443-WS-TLS-09
  - 🇭🇰 移动-HKG-80-WS-10
  - 联通-SJC-443-WS-TLS-01
  - 联通-SJC-80-WS-02
  - 联通-SJC-443-WS-TLS-03
  - 联通-SJC-80-WS-04
  - 联通-SJC-443-WS-TLS-05
  - 联通-SJC-80-WS-06
  - 联通-SJC-443-WS-TLS-07
  - 联通-SJC-80-WS-08
  - 联通-SJC-443-WS-TLS-09
  - 联通-SJC-80-WS-10
  - 电信-SIN-443-WS-TLS-01
  - 电信-SIN-80-WS-02
  - 电信-SIN-443-WS-TLS-03
  - 电信-SIN-80-WS-04
  - 电信-SIN-443-WS-TLS-05
  - 电信-SIN-80-WS-06
  - 电信-SIN-443-WS-TLS-07
  - 电信-SIN-80-WS-08
  - 电信-SIN-443-WS-TLS-09
  - 电信-SIN-80-WS-10
  - 🎯 全球直连
  type: select
- interval: 300
  name: ♻️ 自动选择
  proxies:
  - 🇭🇰 移动-HKG-443-WS-TLS-01
  - 🇭🇰 移动-HKG-80-WS-02
  - 🇭🇰 移动-HKG-443-WS-TLS-03
  - 🇭🇰 移动-HKG-80-WS-04
  - 🇭🇰 移动-HKG-443-WS-TLS-05
  - 🇭🇰 移动-HKG-80-WS-06
  - 🇭🇰 移动-HKG-443-WS-TLS-07
  - 🇭🇰 移动-HKG-80-WS-08
  - 🇭🇰 移动-HKG-443-WS-TLS-09
  - 🇭🇰 移动-HKG-80-WS-10
  - 联通-SJC-443-WS-TLS-01
  - 联通-SJC-80-WS-02
  - 联通-SJC-443-WS-TLS-03
  - 联通-SJC-80-WS-04
  - 联通-SJC-443-WS-TLS-05
  - 联通-SJC-80-WS-06
  - 联通-SJC-443-WS-TLS-07
  - 联通-SJC-80-WS-08
  - 联通-SJC-443-WS-TLS-09
  - 联通-SJC-80-WS-10
  - 电信-SIN-443-WS-TLS-01
  - 电信-SIN-80-WS-02
  - 电信-SIN-443-WS-TLS-03
  - 电信-SIN-80-WS-04
  - 电信-SIN-443-WS-TLS-05
  - 电信-SIN-80-WS-06
  - 电信-SIN-443-WS-TLS-07
  - 电信-SIN-80-WS-08
  - 电信-SIN-443-WS-TLS-09
  - 电信-SIN-80-WS-10
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: 🎯 全球直连
  proxies:
  - DIRECT
  type: select
- name: 🛑 全球拦截
  proxies:
  - REJECT
  type: select
rules:
- DOMAIN-SUFFIX,local,🎯 全球直连
- IP-CIDR,127.0.0.0/8,🎯 全球直连
- IP-CIDR,172.16.0.0/12,🎯 全球直连
- IP-CIDR,192.168.0.0/16,🎯 全球直连
- IP-CIDR,10.0.0.0/8,🎯 全球直连
- IP-CIDR,100.64.0.0/10,🎯 全球直连
- DOMAIN,ad.com,🛑 全球拦截
- DOMAIN,ad.doubler.com,🛑 全球拦截
- DOMAIN-SUFFIX,ad.doubler.com,🛑 全球拦截
- DOMAIN,ad.doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,ad.doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,googlesyndication.com,🛑 全球拦截
- DOMAIN-SUFFIX,googleadservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,doubleclick.net,🛑 全球拦截
- GEOIP,LAN,🎯 全球直连
- GEOIP,CN,🎯 全球直连
- MATCH,🚀 节点选择
