settings:
  auto_update: true
  proxy_groups:
  - name: 🚀 节点选择
    type: select
    use_all_proxies: true
  - interval: 300
    name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    use_all_proxies: true
  retry_count: 3
  timeout: 30
  update_interval: 3600
subscriptions:
- enabled: true
  last_update: '2026-04-09T03:12:04.975278'
  name: 主订阅
  update_interval: 3600
  url: https://url.v1.mk/sub?target=clash&url=https%3A%2F%2Fdy.qlsm.net%2F7782bcd0-7448-4f69-8014-00f6c9867956%2Fsub&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FbyJoey%2Ftest%2Frefs%2Fheads%2Fmain%2Ftist.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
- enabled: true
  last_update: null
  name: 备用订阅
  update_interval: 3600
  url: https://dy.qlsm.net/7782bcd0-7448-4f69-8014-00f6c9867956/sub
